# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          All PGS
baseurl:        ""
url:            "https://allpgs.ga"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         All PGS
  url:          https://allpgs.ga
  email:        kms0219kms@naver.com
  github:       kms0219kms

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/allpgs/allpgs.github.io
